export default {
  APPLICATION_SHOW_MODAL: 'TO_DO_APPLICATION_SHOW_MODAL',
  APPLICATION_HIDE_MODAL: 'TO_DO_APPLICATION_HIDE_MODAL',
  APPLICATION_SHOW_FULLSCREEN_MODAL: 'TO_DO_APPLICATION_SHOW_FULLSCREEN_MODAL',
  APPLICATION_HIDE_FULLSCREEN_MODAL: 'TO_DO_APPLICATION_HIDE_FULLSCREEN_MODAL',
  APPLICATION_PUSH_STACK_FULLSCREEN_MODAL: 'TO_DO_APPLICATION_PUSH_STACK_FULLSCREEN_MODAL',
  APPLICATION_POP_STACK_FULLSCREEN_MODAL: 'TO_DO_APPLICATION_POP_STACK_FULLSCREEN_MODAL',
  AUTH_SET_TOKEN: 'TO_DO_AUTH_SET_TOKEN',
  AUTH_LOGOUT: 'TO_DO_AUTH_LOGOUT',
  AUTH_ERROR: 'TO_DO_AUTH_ERROR',
  AUTH_LOGIN: 'TO_DO_AUTH_LOGIN',

  ADD_TASKS: 'TO_DO_ADD_TASKS',
  FETCH_TASKS: 'TO_DO_FETCH_TASKS',
  SET_TASKS_DATA: 'TO_DO_SET_TASKS_DATA',
  SET_TASKS_ERROR: 'TO_DO_SET_TASKS_ERROR',
  SET_TASKS_LOADING: 'TO_DO_SET_TASKS_LOADING',
  SET_TASKS_TOTAL: 'TO_DO_SET_TASKS_TOTAL'
};
