export default {
  APPLICATION_SHOW_MODAL: 'TO_DO_APPLICATION_SHOW_MODAL',
  APPLICATION_HIDE_MODAL: 'TO_DO_APPLICATION_HIDE_MODAL',
  APPLICATION_SHOW_FULLSCREEN_MODAL: 'TO_DO_APPLICATION_SHOW_FULLSCREEN_MODAL',
  APPLICATION_HIDE_FULLSCREEN_MODAL: 'TO_DO_APPLICATION_HIDE_FULLSCREEN_MODAL',
  APPLICATION_PUSH_STACK_FULLSCREEN_MODAL: 'TO_DO_APPLICATION_PUSH_STACK_FULLSCREEN_MODAL',
  APPLICATION_POP_STACK_FULLSCREEN_MODAL: 'TO_DO_APPLICATION_POP_STACK_FULLSCREEN_MODAL'
};
